admin/models/Alumni.php
<?php

namespace admin\models;

use Yii;

/**
 * This is the model class for table "user".
 *
 * @property int $id
 * @property string $first_name
 * @property string $second_name
 * @property string $gender
 * @property string $username
 * @property int $role
 * @property string $auth_key
 * @property string $password_hash
 * @property string|null $password_reset_token
 * @property string $email
 * @property int $status
 * @property int $created_at
 * @property int $updated_at
 * @property string|null $verification_token
 *
 * @property ResProDetails[] $resProDetails
 * @property ResoureQualification[] $resoureQualifications
 */
class Alumni extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['first_name', 'second_name', 'gender', 'username', 'email'], 'required'],
            [['gender'], 'string'],
            [['role', 'status', 'created_at', 'updated_at'], 'integer'],
            [['first_name', 'second_name'], 'string', 'max' => 155],
            [['password_hash', 'password_reset_token', 'email', 'verification_token'], 'string', 'max' => 255],
            [['auth_key'], 'string', 'max' => 32],
            [['username'], 'unique'],
            [['username'],'match','pattern'=> '/^[0-9]{10}$/','message'=> 'Username can contain only 10 digit number'],
            [['email'], 'unique'],
            [['password_reset_token'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'first_name' => 'First Name',
            'second_name' => 'Last Name',
            'gender' => 'Gender',
            'username' => 'Mobile No',
            'role' => 'Role',
            'auth_key' => 'Auth Key',
            'password_hash' => 'Password Hash',
            'password_reset_token' => 'Password Reset Token',
            'email' => 'Email',
            'status' => 'Login Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'verification_token' => 'Verification Token',
        ];
    }

    /**
     * Gets query for [[ResProDetails]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getProfile()
    {
        return $this->hasOne(AlumniProfile::class, ['ap_uid' => 'id']);
    }
    public function getCompany()
    {
        return $this->hasOne(AlumniCompany::class, ['ac_uid' => 'id']);
    }
    
    public static function getImage($id)
    {
        $imageModel = UserImages::find()->where(['pp_uid' => $id])->one();
        return $imageModel->pp_image;
    }
    public function getCountry($id)
    {
        $countryModel = Countries::find()->where(['id' => $id])->one();
        return $countryModel->name;
    }
    public function getState($id)
    {
        $stateModel = States::find()->where(['id' => $id])->one();
        return $stateModel->name;
    }
    public function getCity($id)
    {
        $cityModel = Cities::find()->where(['id' => $id])->one();
        return $cityModel->name;
    }
}

admin/controllers/AlumniController.php
<?php

namespace admin\controllers;

use Yii;
use admin\models\Alumni;
use admin\models\AlumniCompany;
use admin\models\AlumniProfile;
use admin\models\AlumniSearch;
use admin\models\Cities;
use admin\models\States;
use admin\models\UserImages;
use Behat\Gherkin\Exception\Exception;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\filters\AccessControl;

/**
 * AlumniController implements the CRUD actions for Alumni model.
 */
class AlumniController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['index', 'create', 'update', 'view', 'delete', 'status'],
                'rules' => [
                    [
                        'actions' =>  ['index', 'create', 'update', 'view', 'delete', 'status'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    // 'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Alumni models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AlumniSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Alumni model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
            'profileDetails' => $this->profileModel($id),
        ]);
    }
    public function profileModel($id)
    {
        $profileModel = AlumniProfile::find()->where(['ap_uid' => $id])->one();
        return $profileModel;
    }
    /**
     * Creates a new Alumni model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Alumni();
        $profilePic = new UserImages();
        $alumniProfile = new AlumniProfile();
        $alumniCompany = new AlumniCompany();
        // echo '<pre>';print_r(Yii::$app->request->post('AlumniProfile'));die();
        if ($model->load(Yii::$app->request->post()) && $alumniProfile->load(Yii::$app->request->post()) && $alumniCompany->load(Yii::$app->request->post())) {
            $model->role = '40';
            $model->auth_key = Yii::$app->security->generateRandomString();
            $password = '@Alumni>123';
            $model->password_hash = Yii::$app->security->generatePasswordHash($password);
            $model->status = '9';
            $model->created_at = strtotime(date('Y-m-d H:i:s'));
            $model->updated_at = strtotime(date('Y-m-d H:i:s'));
            $uploadedFile = UploadedFile::getInstance($profilePic, 'pp_image');
            if (!empty($uploadedFile)) {
                $profileName = preg_replace('/\s+/', '', $model->first_name);
                $profileImg = $profileName . '_' . $uploadedFile;
            } else {
                $profileImg = 'user.png';
            }
            if ($model->save()) {
                if (!empty($profileImg)) {
                    $profilePic->pp_uid = $model->id;
                    $profilePic->pp_image = $profileImg;
                    $profilePic->pp_status = 'Active';
                    if ($profilePic->save()) {
                        if (!empty($uploadedFile)) {
                            $uploadedFile->saveAs('../theme/img/pro_images/alumni/' . $profileImg);
                        }
                    }
                }

                $alumniProfile->ap_uid = $model->id;
                $alumniProfile->ap_approved_uid = Yii::$app->user->id;
                $alumniProfile->ap_class = '0';
                $alumniCompany->ac_uid = $model->id;

                $transaction = Yii::$app->db->beginTransaction();
                try {
                    if ($alumniProfile->save() && $alumniCompany->save()) {
                        $transaction->commit();
                    } else {
                        $transaction->rollBack();
                    }
                } catch (Exception $e) {
                    $transaction->rollBack();
                }
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                    'alumniProfile' => $alumniProfile,
                    'profilePic' => $profilePic,
                    'alumniCompany' => $alumniCompany,
                ]);
            }
        }

        return $this->render('create', [
            'model' => $model,
            'profilePic' => $profilePic,
            'alumniCompany' => $alumniCompany,
            'alumniProfile' => $alumniProfile,
        ]);
    }

    /**
     * Updates an existing Alumni model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $profilePic = UserImages::find()->where(['pp_uid' => $id])->one();
        $alumniProfile = AlumniProfile::find()->where(['ap_uid' => $id])->one();
        $alumniCompany = AlumniCompany::find()->where(['ac_uid' => $id])->one();
        $old_image = $profilePic->pp_image;
        $uploadedFile = UploadedFile::getInstance($profilePic, 'pp_image');
        if (!empty($uploadedFile)) {
            $profileName = preg_replace('/\s+/', '', $model->first_name);
            $profileImg = $profileName . '_' . $uploadedFile;
        } else {
            $profileImg = $old_image;
        }

        if ($model->load(Yii::$app->request->post()) && $alumniProfile->load(Yii::$app->request->post()) && $alumniCompany->load(Yii::$app->request->post())) {
            if (!empty($profileImg)) {
                $profilePic->pp_uid = $model->id;
                $profilePic->pp_image = $profileImg;
                $profilePic->pp_status = 'Active';
                if ($profilePic->save()) {
                    if (!empty($uploadedFile)) {
                        $uploadedFile->saveAs('../theme/img/pro_images/alumni/' . $profileImg);
                    }
                }
            }

            $alumniProfile->ap_uid = $model->id;
            $alumniProfile->ap_approved_uid = Yii::$app->user->id;
            $alumniProfile->ap_class = '0';
            $alumniCompany->ac_uid = $model->id;

            $transaction = Yii::$app->db->beginTransaction();
            try {
                if ($alumniProfile->save() && $alumniCompany->save()) {
                    $transaction->commit();
                } else {
                    $transaction->rollBack();
                }
            } catch (Exception $e) {
                $transaction->rollBack();
            }
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'alumniProfile' => $alumniProfile,
                'profilePic' => $profilePic,
                'alumniCompany' => $alumniCompany,
            ]);
        }

        return $this->render('update', [
            'model' => $model,
            'profilePic' => $profilePic,
            'alumniProfile' => $alumniProfile,
            'alumniCompany' => $alumniCompany,
        ]);
    }

    /**
     * Deletes an existing Alumni model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
    public static function actionState()
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $parents = $_POST['depdrop_parents'];
            if ($parents != null) {
                $country_id = $parents[0];
                $out = States::find()->where(['country_id' => $country_id])->all();
                // the getSubCatList function will query the database based on the
                // cat_id and return an array like below:
                // [
                //    ['id'=>'<sub-cat-id-1>', 'name'=>'<sub-cat-name1>'],
                //    ['id'=>'<sub-cat_id_2>', 'name'=>'<sub-cat-name2>']
                // ]
                return ['output' => $out, 'selected' => ''];
            }
        }
        return ['output' => '', 'selected' => ''];
    }

    public static function actionCity()
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $parents = $_POST['depdrop_parents'];
            if ($parents != null) {
                $state_id = $parents[0];
                $out = Cities::find()->where(['state_id' => $state_id])->all();
                // the getSubCatList function will query the database based on the
                // cat_id and return an array like below:
                // [
                //    ['id'=>'<sub-cat-id-1>', 'name'=>'<sub-cat-name1>'],
                //    ['id'=>'<sub-cat_id_2>', 'name'=>'<sub-cat-name2>']
                // ]

admin/views/alumni/_form.php
<?php

use admin\models\Countries;
use kartik\file\FileInput;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\depdrop\DepDrop;
use yii\helpers\Url;


/* @var $this yii\web\View */
/* @var $model admin\models\Alumni */
/* @var $form yii\widgets\ActiveForm */

$Country = Countries::find()->all();
$listData = ArrayHelper::map($Country, 'id', 'name');
?>

<div class="alumni-form">

    <?php $form = ActiveForm::begin(); ?>

    <div class="row">
        <div class="col-md-12">
            <?php echo $form->field($profilePic, 'pp_image')->widget(FileInput::class, [
                'options' => ['accept' => 'image/*'],
            ]);
            ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'first_name')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'second_name')->textInput(['maxlength' => true]) ?>
        </div>

        <div class="col-md-4">
            <?= $form->field($model, 'gender')->dropDownList(['Male' => 'Male', 'Female' => 'Female', 'Transgender' => 'Transgender',], ['prompt' => '-- Select Gender --']) ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-12">
            <h5>Personal Profile Details</h5>
        </div>
        <div class="col-md-12">
            <?= $form->field($alumniProfile, 'ap_address')->textarea(['rows' => 1]) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($alumniProfile, 'ap_country')->dropDownList($listData, ['id' => 'country-id', 'prompt' => '--Choose Country--']); ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($alumniProfile, 'ap_state')->widget(DepDrop::class, [
                'options' => ['id' => 'state-id'],
                'pluginOptions' => [
                    'depends' => ['country-id'],
                    'placeholder' => '--Choose State--',
                    'url' => Url::to(['/alumni/state'])
                ]
            ]); ?>

        </div>
        <div class="col-md-3">
            <?= $form->field($alumniProfile, 'ap_city')->widget(DepDrop::class, [
                'pluginOptions' => [
                    'depends' => ['state-id'],
                    'placeholder' => '--Choose City--',
                    'url' => Url::to(['/alumni/city'])
                ]
            ]); ?>

        </div>
        <div class="col-md-3">
            <?= $form->field($alumniProfile, 'ap_pincode')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-6">
            <?= $form->field($alumniProfile, 'ap_batch_from')->widget(\yii\jui\DatePicker::class, [
                //'language' => 'ru',
                'dateFormat' => 'yyyy-MM-dd',
                'options' => ['class' => 'form-control'],
            ]) ?>
        </div>
        <div class="col-md-6">
            <?= $form->field($alumniProfile, 'ap_batch_to')->widget(\yii\jui\DatePicker::class, [
                //'language' => 'ru',
                'dateFormat' => 'yyyy-MM-dd',
                'options' => ['class' => 'form-control'],
            ]) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($alumniProfile, 'ap_qualification')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($alumniProfile, 'ap_linkedin_link')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($alumniProfile, 'ap_facebook_link')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($alumniProfile, 'ap_twitter_link')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-12">
            <h5>Company Profile Details</h5>
        </div>
        <div class="col-md-6">
            <?= $form->field($alumniCompany, 'ac_postion')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-6">
            <?= $form->field($alumniCompany, 'ac_name')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($alumniCompany, 'ac_joined_date')->widget(\yii\jui\DatePicker::class, [
                //'language' => 'ru',
                'dateFormat' => 'yyyy-MM-dd',
                'options' => ['class' => 'form-control'],
            ]) ?>

        </div>
        <div class="col-md-3">
            <?= $form->field($alumniCompany, 'ac_relieved_date')->widget(\yii\jui\DatePicker::class, [
                //'language' => 'ru',
                'dateFormat' => 'yyyy-MM-dd',
                'options' => ['class' => 'form-control'],
            ]) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($alumniCompany, 'ac_location')->textInput() ?>

        </div>
        <div class="col-md-3">
            <?= $form->field($alumniCompany, 'ac_status')->dropDownList(['Active' => 'Yes', 'Inactive' => 'No'], ['prompt' => '--Select Status--']) ?>
        </div>
    </div>



    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

admin/views/alumni/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model admin\models\AlumniSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="alumni-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'first_name') ?>

    <?= $form->field($model, 'second_name') ?>

    <?= $form->field($model, 'gender') ?>

    <?= $form->field($model, 'username') ?>

    <?php // echo $form->field($model, 'role') ?>

    <?php // echo $form->field($model, 'auth_key') ?>

    <?php // echo $form->field($model, 'password_hash') ?>

    <?php // echo $form->field($model, 'password_reset_token') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'verification_token') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

admin/views/alumni/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model admin\models\Alumni */

$this->title = 'Add New Alumni';
$this->params['breadcrumbs'][] = ['label' => 'Alumnis', 'url' => ['index']];
$this->params['breadcrumbs'][] = '>';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="alumni-create view-block">

    <h3><?= Html::encode($this->title) ?></h3>

    <?= $this->render('_form', [
        'model' => $model,
        'alumniProfile' => $alumniProfile,
        'profilePic' => $profilePic,
        'alumniCompany' => $alumniCompany,
    ]) ?>

</div>

admin/views/alumni/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel admin\models\AlumniSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Alumnis';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="alumni-index">

    <h1><?= Html::encode($this->title) ?>

        <?= Html::a('Add Alumni', ['create'], ['class' => 'btn btn-success pull-right']) ?>

    </h1>
    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); 
    ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            // 'id',
            [
                'attribute' => 'first_name',
                'format' => 'html',
                'label' => 'Name',
                'value' => function ($data) {
                    return $data->first_name . ' ' . $data->second_name;
                },
            ],
            'username',
            //'role',
            //'auth_key',
            //'password_hash',
            //'password_reset_token',
            'email:email',
            // 'status',
            'created_at:date',
            //'updated_at',
            //'verification_token',

            [
                'headerOptions' => ['width' => '250'],
                'class' => 'yii\grid\ActionColumn',
                'header' => 'Actions',
                'template' => '{view} {update} {delete} {status}',
                'buttons' => [
                    'delete' => function ($url, $model) {
                        return Html::a('', $url, [
                            'class' => 'btn btn-danger fa fa-trash',
                            'title' => Yii::t('app', 'Delete'), 'data-confirm' => Yii::t('app', 'Are you sure you want to delete this image?'), 'data-method' => 'post'
                        ]);
                    },
                    'update' => function ($url, $model) {
                        return Html::a('', $url, [
                            'class' => 'btn btn-primary fas fa-pencil-alt',
                            'title' => Yii::t('app', 'Update Slider')
                        ]);
                    },
                    'view' => function ($url, $model) {
                        return Html::a('', $url, [
                            'class' => 'btn btn-info fas fa-eye',
                            'title' => Yii::t('app', 'View Slider')
                        ]);
                    },
                    'status' => function ($url, $model) {
                        return $model->profile['ap_approved_uid'] == 0 ?
                        Html::a('', $url, [
                            'class' => 'btn btn-success fas fa-check',
                            'title' => Yii::t('app', ' Approve Alumni')
                        ]) : Html::a('', $url, [
                            'class' => 'btn btn-warning fas fa-window-close',
                            'title' => Yii::t('app', 'Reject Alumni')
                        ]);
                    },
                    
                ],

            ],
        ],
    ]);
    ?>

    <?php Pjax::end(); ?>

</div>

admin/views/alumni/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model admin\models\Alumni */

$this->title = 'Update: ' . $model->first_name.' '.$model->second_name;
$this->params['breadcrumbs'][] = ['label' => 'Alumnis', 'url' => ['index']];
$this->params['breadcrumbs'][] = '>';
$this->params['breadcrumbs'][] = ['label' => $model->first_name.' '.$model->second_name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = '>';
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="alumni-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'alumniProfile' => $alumniProfile,
        'profilePic' => $profilePic,
        'alumniCompany' => $alumniCompany,
    ]) ?>

</div>

admin/views/alumni/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model admin\models\Alumni */

$this->title = $model->first_name . ' ' . $model->second_name;
$this->params['breadcrumbs'][] = ['label' => 'Alumnis', 'url' => ['index']];
$this->params['breadcrumbs'][] = '>';
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="alumni-view">

    <h1><?= Html::encode($this->title) ?>

        <span class="pull-right">
            <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
            <?= Html::a('Delete', ['delete', 'id' => $model->id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => 'Are you sure you want to delete this item?',
                    'method' => 'post',
                ],
            ]) ?>
        </span>
    </h1>
    <div class="row">
        <div class="col-lg-12 view-block">
            <h4>Alumni Profile Details</h4>
            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    // 'id',
                    [
                        'attribute' => 'Status',
                        'label' => 'Profile Image',
                        'value' => Yii::$app->homeUrl . '../theme/img/pro_images/alumni/' . $model->getImage($model->id),
                        'format' => ['image', ['width' => '100', 'height' => '100']],
                    ],
                    'first_name',
                    'second_name',
                    'gender',
                    'username',
                    'email:email',
                    [
                        'attribute' => 'status',
                        'value' => function ($model) {
                            return $model->status = '9' ? 'Inactive' : 'Active';
                        },
                    ],
                    'created_at:date',
                    'updated_at:date',
                ],
            ]) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 view-block">
            <h4>Alumni Communication Details</h4>
            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'profile.ap_batch_from:date',
                    'profile.ap_batch_to:date',
                    'profile.ap_address',
                    [
                        'attribute' => 'Country',
                        'value' => $model->getCountry($model->profile->ap_country),
                    ],
                    [
                        'attribute' => 'State',
                        'value' => $model->getState($model->profile->ap_state),
                    ],
                    [
                        'attribute' => 'City',
                        'value' => $model->getCity($model->profile->ap_city),
                    ],
                    'profile.ap_pincode',
                    'profile.ap_qualification',
                    [
                        'attribute' => 'ap_linkedin_link',
                        'label' => 'LinkedIn Link',
                        'value' => function ($model) {
                            return $model->profile->ap_linkedin_link == '' ? 'Not Available' : $model->profile->ap_linkedin_link;
                        },
                    ],
                    [
                        'attribute' => 'ap_facebook_link',
                        'label' => 'Facebook Link',
                        'value' => function ($model) {
                            return $model->profile->ap_facebook_link == '' ? 'Not Available' : $model->profile->ap_facebook_link;
                        },
                    ],
                    [
                        'attribute' => 'ap_twitter_link',
                        'label' => 'Twitter Link',
                        'value' => function ($model) {
                            return $model->profile->ap_twitter_link == '' ? 'Not Available' : $model->profile->ap_twitter_link;
                        },
                    ],
                ],
            ]) ?>
        </div>
        <div class="col-md-12 view-block">
            <h4>Alumni Company Details</h4>
            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'company.ac_postion',
                    'company.ac_name',
                    'company.ac_joined_date:date',
                    'company.ac_relieved_date:date',
                    'company.ac_location',
                    [
                        'attribute' => 'company.ac_status',
                        'label' => 'Current Company',
                        'value' => function ($model) {
                            return $model->company->ac_status = 'Active' ? 'Yes' : 'No';
                        },
                    ],
                ],
            ]) ?>
        </div>
    </div>
</div>